### ISSUE TITLE
Project....

### ISSUE THREAD

**Issue by adrihd** [getoffmyhack/RTLSDR.Swift#2]
Do you fancy starting a project up so we can work on getting librtlsdr and associated libs ported? I'd be happy to help.  I mean to swift.

**Comment by getoffmyhack** [comment]
Hey,

Thanks for reaching out to me and sorry I haven’t responded sooner.  Anyway, I had put my RTLSDR.Swift project on the back burner before COVID and just haven’t had the inspiration to do much work on it in the last few months.  Granted, I fully intend on finishing the port to Swift, especially since there has been a flurry of development in recent weeks on one of the main forks of librtlsdr (https://github.com/librtlsdr/librtlsdr <https://github.com/librtlsdr/librtlsdr> , check out the development branch.)

To be honest, I am not much of a macOS programmer, so I am a bit behind on the latest  macOS / Swift features, ie swift packages, but I am also looking forward to learning all the new stuff once I get back into writing macOS code (been working on low level AVR and STM32 micro controller code.)

Considering your interest in helping, lets start pushing this project forward, especially since it's a small part of my larger project, waveSDR (https://github.com/getoffmyhack/waveSDR <https://github.com/getoffmyhack/waveSDR>), its time I get inspired to start working on that project as well.

Going forward, contact me at waveSDR [-  a  t  -] getoffmyhack.com and let's put together a plan to get a working macOS native RTLSDR driver.

Again, thanks for reaching out to me.

Justin
